#!/bin/bash

# No need to bump any version numbers. We always fetch the latest version.
install_version=$(curl http://builds.piwik.org/LATEST)

# Download and install Piwik
install_dir=${OPENSHIFT_BUILD_DEPENDENCIES_DIR}${install_version}

# Used in this script only
current_version_dir=${OPENSHIFT_DATA_DIR}current

# If Piwik is already installed in the current gear, there
# is nothing to build :-)
[ -d "${current_version_dir}" ] && exit 0
mkdir -p $install_dir
pushd ${install_dir} >/dev/null
curl -O http://builds.piwik.org/piwik-${install_version}.tar.gz

# Extract and install Piwik
tar --strip-components=1 -xzf piwik-${install_version}.tar.gz
rm -rf piwik-${install_version}.tar.gz
echo $install_version > ${OPENSHIFT_BUILD_DEPENDENCIES_DIR}.current_version

popd >/dev/null
